hydra:
  run:
    dir: outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra.job.num}
  launcher:
    _target_: hydra._internal.core_plugins.basic_launcher.BasicLauncher
  sweeper:
    _target_: hydra._internal.core_plugins.basic_sweeper.BasicSweeper
    max_batch_size: null
  help:
    app_name: ${hydra.job.name}
    header: '${hydra.help.app_name} is powered by Hydra.

      '
    footer: 'Powered by Hydra (https://hydra.cc)

      Use --hydra-help to view Hydra specific help

      '
    template: '${hydra.help.header}

      == Configuration groups ==

      Compose your configuration from those groups (group=option)


      $APP_CONFIG_GROUPS


      == Config ==

      Override anything in the config (foo.bar=value)


      $CONFIG


      ${hydra.help.footer}

      '
  hydra_help:
    template: 'Hydra (${hydra.runtime.version})

      See https://hydra.cc for more info.


      == Flags ==

      $FLAGS_HELP


      == Configuration groups ==

      Compose your configuration from those groups (For example, append hydra/job_logging=disabled
      to command line)


      $HYDRA_CONFIG_GROUPS


      Use ''--cfg hydra'' to Show the Hydra config.

      '
    hydra_help: ???
  hydra_logging:
    version: 1
    formatters:
      simple:
        format: '[%(asctime)s][HYDRA] %(message)s'
    handlers:
      console:
        class: logging.StreamHandler
        formatter: simple
        stream: ext://sys.stdout
    root:
      level: INFO
      handlers:
      - console
    loggers:
      logging_example:
        level: DEBUG
    disable_existing_loggers: false
  job_logging:
    version: 1
    formatters:
      simple:
        format: '[%(asctime)s][%(name)s][%(levelname)s] - %(message)s'
    handlers:
      console:
        class: logging.StreamHandler
        formatter: simple
        stream: ext://sys.stdout
      file:
        class: logging.FileHandler
        formatter: simple
        filename: ${hydra.job.name}.log
    root:
      level: INFO
      handlers:
      - console
      - file
    disable_existing_loggers: false
  env: {}
  searchpath: []
  callbacks: {}
  output_subdir: .hydra
  overrides:
    hydra: []
    task: []
  job:
    name: pipeline
    override_dirname: ''
    id: ???
    num: ???
    config_name: config
    env_set: {}
    env_copy: []
    config:
      override_dirname:
        kv_sep: '='
        item_sep: ','
        exclude_keys: []
  runtime:
    version: 1.1.0
    cwd: /home/yanjie/zyj_test/virtual-multi-view
    config_sources:
    - path: hydra.conf
      schema: pkg
      provider: hydra
    - path: /home/yanjie/zyj_test/virtual-multi-view/config
      schema: file
      provider: main
    - path: ''
      schema: structured
      provider: schema
    choices:
      hydra/env: default
      hydra/callbacks: null
      hydra/job_logging: default
      hydra/hydra_logging: default
      hydra/hydra_help: default
      hydra/help: default
      hydra/sweeper: basic
      hydra/launcher: basic
      hydra/output: default
  verbose: false
dataset:
  root_path: /data/ScanNetV2
  train_path: /data/ScanNetV2/scans
  test_path: /data/ScanNetV2/scans_test
  label_map: /data/ScanNetV2/scannetv2-labels.combined.tsv
  real_view: true
  image_num_percentage: 1.0
device: cuda:0
model:
  model_name: deeplabv3+
  backbone: xception
  pretrain: false
  pretrained_model_path: None
  num_classes: 21
  output_stride: 16
  num_channels: 3
  save_model_path: /home/yanjie/zyj_test/virtual-multi-view/checkpoint/
evaluation:
  model_path: /home/yanjie/zyj_test/virtual-multi-view/checkpoint/deeplabv3+_epoch4.pth
optimizer:
  name: Adam
  learning_rate: 1.0e-05
  weight_decay: 0.99
data_loader:
  batch_size: 2
  num_workers: 4
num_epoch: 5
render:
  img_size: 256
  camera_dist: 3
  elevation: 0
  azim_angle: 0
benchmark_labels:
- wall
- floor
- cabinet
- bed
- chair
- sofa
- table
- door
- window
- bookshelf
- picture
- counter
- desk
- curtain
- refrigerator
- shower curtain
- toilet
- sink
- bathtub
- otherfurniture
valid_class_ids:
- 1
- 2
- 3
- 4
- 5
- 6
- 7
- 8
- 9
- 10
- 11
- 12
- 14
- 16
- 24
- 28
- 33
- 34
- 36
- 39
visdom:
  use: true
  env: YanjieZe
