dataset:
  root_path: /data/ScanNetV2
  train_path: /data/ScanNetV2/scans
  test_path: /data/ScanNetV2/scans_test
  label_map: /data/ScanNetV2/scannetv2-labels.combined.tsv
  image_form: color
  real_view: True # this means we use real view, not virtual view
  image_num_percentage: 1.0 # from 0 to 1, to sample image from the image dataset

device: "cuda:1"

  
model:
  model_name: deeplabv3+
  backbone: xception
  pretrain: False
  pretrained_model_path: /home/yanjie/zyj_test/virtual-multi-view/checkpoint/???
  # mobilenet: /home/yanjie/.cache/torch/hub/checkpoints/mobilenet_v2-6a65762b.pth
  num_classes: 40
  output_stride: 16

optimizer:
  name: Adam
  learning_rate: 1e-5
  weight_decay: 0.99

data_loader:
  batch_size: 1
  num_workers: 2

num_epoch: 5

render:
  img_size: 256
  camera_dist: 3
  elevation: 0
  azim_angle: 0
