dataset:
  root_path: /data/ScanNetV2
  train_path: /data/ScanNetV2/scans
  test_path: /data/ScanNetV2/scans_test
  label_map: /data/ScanNetV2/scannetv2-labels.combined.tsv
  real_view: False # If this is ture, we use real view img. Otherwise, we use virtual view img.
  virtual_img_root: /home/yanjie/zyj_test/virtual-multi-view/virtual_img_dataset


device: "cuda:1"

  
model:
  model_name: deeplabv3+ # choice: unet, deeplabv3+

  # --------------if model is deeplabv3+------------------#
  backbone: xception # choice: resnet, drn, mobilenet, xception
  # ------------------------------------------------------#

  pretrain: False
  pretrained_model_path: None
  # mobilenet: /home/yanjie/.cache/torch/hub/checkpoints/mobilenet_v2-6a65762b.pth
  num_classes: 20
  output_stride: 8
  num_channels: 3
  save_model_path: /home/yanjie/zyj_test/virtual-multi-view/checkpoint/


evaluation: 
  model_path: /home/yanjie/zyj_test/virtual-multi-view/checkpoint/deeplabv3+_epoch19.pth

optimizer:
  name: Adam
  learning_rate: 1e-3
  weight_decay: 0.0001

data_loader:
  batch_size: 2
  num_workers: 4

num_epoch: 50

render:
  img_size: 256
  camera_dist: 3
  elevation: 0
  azim_angle: 0

# create virtual imgs
img_creator:
  save_path: /home/yanjie/zyj_test/virtual-multi-view/virtual_img_dataset/
  fx: 300
  fy: 200
  cx: 640
  cy: 680
  width: 960
  height: 480
  scene_num: 10


visdom:
  use: False
  env: YanjieZe

# Here are 20 classes used in the benchmark
# we set background and other furnitures as one class
# This means, the background's id is 39(origin) and 0(in benchmark)
benchmark_labels: ['otherfurniture and background', 'wall', 'floor', 'cabinet', 'bed', 'chair', 'sofa', 'table', 'door', 'window', 'bookshelf', 'picture', 'counter', 'desk', 'curtain', 'refrigerator', 'shower curtain', 'toilet', 'sink', 'bathtub']
valid_class_ids: [39, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 14, 16, 24, 28, 33, 34, 36]




